// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file proto/payments/payments.proto (package api.payments, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/payments/payments.proto.
 */
export const file_proto_payments_payments: GenFile = /*@__PURE__*/
  fileDesc("Ch1wcm90by9wYXltZW50cy9wYXltZW50cy5wcm90bxIMYXBpLnBheW1lbnRzIjgKGkNyZWF0ZVBheW1lbnRJbnRlbnRSZXF1ZXN0EhoKDnJlc2VydmF0aW9uX2lkGAEgASgDQgIwASI0ChtDcmVhdGVQYXltZW50SW50ZW50UmVzcG9uc2USFQoNY2xpZW50X3NlY3JldBgBIAEoCTJ9Cg9QYXltZW50c1NlcnZpY2USagoTQ3JlYXRlUGF5bWVudEludGVudBIoLmFwaS5wYXltZW50cy5DcmVhdGVQYXltZW50SW50ZW50UmVxdWVzdBopLmFwaS5wYXltZW50cy5DcmVhdGVQYXltZW50SW50ZW50UmVzcG9uc2VCnwEKEGNvbS5hcGkucGF5bWVudHNCDVBheW1lbnRzUHJvdG9QAVorYXBpL2ludGVybmFsL3Byb3RvL3BheW1lbnRzO3BheW1lbnRzc2VydmljZaICA0FQWKoCDEFwaS5QYXltZW50c8oCDEFwaVxQYXltZW50c+ICGEFwaVxQYXltZW50c1xHUEJNZXRhZGF0YeoCDUFwaTo6UGF5bWVudHNiBnByb3RvMw");

/**
 * @generated from message api.payments.CreatePaymentIntentRequest
 */
export type CreatePaymentIntentRequest = Message<"api.payments.CreatePaymentIntentRequest"> & {
  /**
   * @generated from field: int64 reservation_id = 1 [jstype = JS_STRING];
   */
  reservationId: string;
};

/**
 * Describes the message api.payments.CreatePaymentIntentRequest.
 * Use `create(CreatePaymentIntentRequestSchema)` to create a new message.
 */
export const CreatePaymentIntentRequestSchema: GenMessage<CreatePaymentIntentRequest> = /*@__PURE__*/
  messageDesc(file_proto_payments_payments, 0);

/**
 * @generated from message api.payments.CreatePaymentIntentResponse
 */
export type CreatePaymentIntentResponse = Message<"api.payments.CreatePaymentIntentResponse"> & {
  /**
   * @generated from field: string client_secret = 1;
   */
  clientSecret: string;
};

/**
 * Describes the message api.payments.CreatePaymentIntentResponse.
 * Use `create(CreatePaymentIntentResponseSchema)` to create a new message.
 */
export const CreatePaymentIntentResponseSchema: GenMessage<CreatePaymentIntentResponse> = /*@__PURE__*/
  messageDesc(file_proto_payments_payments, 1);

/**
 * @generated from service api.payments.PaymentsService
 */
export const PaymentsService: GenService<{
  /**
   * @generated from rpc api.payments.PaymentsService.CreatePaymentIntent
   */
  createPaymentIntent: {
    methodKind: "unary";
    input: typeof CreatePaymentIntentRequestSchema;
    output: typeof CreatePaymentIntentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_payments_payments, 0);

