version: '3'

dotenv: [.env]

tasks:
  default:
    desc: Display all tasks
    cmds:
      - task: list
  
  list:
    desc: List all tasks
    cmds:
      - task -l

  gen:proto:
    desc: Generate proto
    cmds:
      - buf generate

  clean:bun:
    desc: clean files
    cmds:
      - cd app && bun run clean
  lint:bun:
    desc: lint files
    cmds: 
      - cd app && bun run check:fix
  typecheck:
    desc: typecheck files
    cmds:
      - cd app && bun run typecheck
  dev:bun:
    desc: start dev server
    cmds:
      - cd app && bun --bun --env-file=../.env run dev
  dev:
    desc: start dev go and bun servers
    cmds:
      - concurrently "cd api && air -c .air.toml" "cd app && bun --bun --env-file=../.env run dev"
  dev:go:
    desc: start dev go server
    cmds:
      - cd api && air -c .air.toml
  install:bun:
    desc: install dependencies
    cmds:
      - cd app && bun install
  install:go:
    desc: install dependencies
    cmds:
      - cd api && go mod tidy
  install:
    desc: install dependencies
    cmds:
      - task install:bun
      - task install:go
  bun:
    desc: run bun commands
    cmds:
      - cd app && bun {{.CLI_ARGS}}
