version: '3'
env:
  API_ROOT: ./api
  NEXT_ROOT: ./app
  WWW_ROOT: ./www

dotenv: [.env]

tasks:
  default:
    desc: Display all tasks
    cmds:
      - task: list
  
  list:
    desc: List all tasks
    cmds:
      - task -l

  gen:proto:
    desc: Generate proto
    cmds:
      - buf generate
  gen:types:
    desc: Generate next route types
    dir: "{{.NEXT_ROOT}}"
    cmds:
      - bun --bun --env-file=../.env run typegen
  clean:
    desc: clean files
    dir: "{{.NEXT_ROOT}}"
    cmds:
      - bun run clean
  lint:bun:
    desc: lint ts files
    dir: "{{.NEXT_ROOT}}"
    cmds: 
      - bun run check:fix
  lint:go:
    dir: "{{.API_ROOT}}"
    desc: lint go files
    cmds:
      - golangci-lint run -c .golangci.yml
  lint:types:
    dir: "{{.NEXT_ROOT}}"
    desc: typecheck typescript files
    cmds:
      - bun --bun run typecheck
  lint:
    desc: lint all files
    cmds:
      - task: lint:bun
      - task: lint:go
      - task: lint:types
  dev:bun:
    desc: start dev server
    cmds:
      - cd app && bun --bun --env-file=../.env run dev
  
  dev:
    desc: start dev go and bun servers
    cmds:
      - concurrently --names "API,APP" --prefix "[{name}]" --prefix-colors "blue,magenta" "cd api && air -c .air.toml" "cd app && bun --env-file=../.env run dev"
  dev:build:
    desc: build front end and run and start dev backend
    cmds:
      - task build:bun
      - concurrently --names "API,APP" --prefix "[{name}]" --prefix-colors "blue,magenta" "cd api && air -c .air.toml" "cd app && bun --env-file=../.env run next start"

  dev:go:
    desc: start dev go server
    dir: "{{.API_ROOT}}"
    cmds:
      - air -c .air.toml -- -env ../.env
  dev:www:
    desc: start dev www server
    dir: "{{.WWW_ROOT}}" 
    cmds:
      - air -c .air.toml
  install:bun:
    desc: install dependencies
    cmds:
      - cd app && bun install
  install:go:
    desc: install dependencies
    cmds:
      - cd api && go mod tidy
  install:
    desc: install dependencies
    cmds:
      - task install:bun
      - task install:go
  bun:
    desc: run bun commands
    dir: "{{.NEXT_ROOT}}"
    cmds:
      - bun {{.CLI_ARGS}}
  go: 
    desc: run go commands
    dir: "{{.API_ROOT}}"
    cmds:
      - go {{.CLI_ARGS}}
  build:bun:
    desc: build bun app
    dir: "{{.NEXT_ROOT}}"
    cmds:
      - bun run build
  build:go:
    desc: build go app
    dir: "{{.API_ROOT}}"
    cmds:
      - go build -o bin/main main.go
  build:
    desc: build all apps
    cmds:
      - task build:bun
      - task build:go
