// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/payments/payments.proto

package paymentsservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

type CreatePaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientSecret  string                 `protobuf:"bytes,1,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

var File_proto_payments_payments_proto protoreflect.FileDescriptor

const file_proto_payments_payments_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/payments/payments.proto\x12\fapi.payments\"G\n" +
	"\x1aCreatePaymentIntentRequest\x12)\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03B\x020\x01R\rreservationId\"B\n" +
	"\x1bCreatePaymentIntentResponse\x12#\n" +
	"\rclient_secret\x18\x01 \x01(\tR\fclientSecret2}\n" +
	"\x0fPaymentsService\x12j\n" +
	"\x13CreatePaymentIntent\x12(.api.payments.CreatePaymentIntentRequest\x1a).api.payments.CreatePaymentIntentResponseB\x9f\x01\n" +
	"\x10com.api.paymentsB\rPaymentsProtoP\x01Z+api/internal/proto/payments;paymentsservice\xa2\x02\x03APX\xaa\x02\fApi.Payments\xca\x02\fApi\\Payments\xe2\x02\x18Api\\Payments\\GPBMetadata\xea\x02\rApi::Paymentsb\x06proto3"

var (
	file_proto_payments_payments_proto_rawDescOnce sync.Once
	file_proto_payments_payments_proto_rawDescData []byte
)

func file_proto_payments_payments_proto_rawDescGZIP() []byte {
	file_proto_payments_payments_proto_rawDescOnce.Do(func() {
		file_proto_payments_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payments_payments_proto_rawDesc), len(file_proto_payments_payments_proto_rawDesc)))
	})
	return file_proto_payments_payments_proto_rawDescData
}

var file_proto_payments_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_payments_payments_proto_goTypes = []any{
	(*CreatePaymentIntentRequest)(nil),  // 0: api.payments.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil), // 1: api.payments.CreatePaymentIntentResponse
}
var file_proto_payments_payments_proto_depIdxs = []int32{
	0, // 0: api.payments.PaymentsService.CreatePaymentIntent:input_type -> api.payments.CreatePaymentIntentRequest
	1, // 1: api.payments.PaymentsService.CreatePaymentIntent:output_type -> api.payments.CreatePaymentIntentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payments_payments_proto_init() }
func file_proto_payments_payments_proto_init() {
	if File_proto_payments_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payments_payments_proto_rawDesc), len(file_proto_payments_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payments_payments_proto_goTypes,
		DependencyIndexes: file_proto_payments_payments_proto_depIdxs,
		MessageInfos:      file_proto_payments_payments_proto_msgTypes,
	}.Build()
	File_proto_payments_payments_proto = out.File
	file_proto_payments_payments_proto_goTypes = nil
	file_proto_payments_payments_proto_depIdxs = nil
}
