// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/payments/payments.proto

package paymentsservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

type CreatePaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientSecret  string                 `protobuf:"bytes,1,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type GetStripePublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStripePublicKeyRequest) Reset() {
	*x = GetStripePublicKeyRequest{}
	mi := &file_proto_payments_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStripePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStripePublicKeyRequest) ProtoMessage() {}

func (x *GetStripePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStripePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetStripePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{2}
}

type GetStripePublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStripePublicKeyResponse) Reset() {
	*x = GetStripePublicKeyResponse{}
	mi := &file_proto_payments_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStripePublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStripePublicKeyResponse) ProtoMessage() {}

func (x *GetStripePublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStripePublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetStripePublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{3}
}

func (x *GetStripePublicKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type CreatePaymentSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentSessionResponse) Reset() {
	*x = CreatePaymentSessionResponse{}
	mi := &file_proto_payments_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentSessionResponse) ProtoMessage() {}

func (x *CreatePaymentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentSessionResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentSessionResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ValidatePaymentSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReservationId int64                  `protobuf:"varint,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentSessionRequest) Reset() {
	*x = ValidatePaymentSessionRequest{}
	mi := &file_proto_payments_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentSessionRequest) ProtoMessage() {}

func (x *ValidatePaymentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidatePaymentSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatePaymentSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ValidatePaymentSessionRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

type ValidatePaymentSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentSessionResponse) Reset() {
	*x = ValidatePaymentSessionResponse{}
	mi := &file_proto_payments_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentSessionResponse) ProtoMessage() {}

func (x *ValidatePaymentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidatePaymentSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{6}
}

func (x *ValidatePaymentSessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_payments_payments_proto protoreflect.FileDescriptor

const file_proto_payments_payments_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/payments/payments.proto\x12\fapi.payments\"G\n" +
	"\x1aCreatePaymentIntentRequest\x12)\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03B\x020\x01R\rreservationId\"B\n" +
	"\x1bCreatePaymentIntentResponse\x12#\n" +
	"\rclient_secret\x18\x01 \x01(\tR\fclientSecret\"\x1b\n" +
	"\x19GetStripePublicKeyRequest\";\n" +
	"\x1aGetStripePublicKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"0\n" +
	"\x1cCreatePaymentSessionResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"i\n" +
	"\x1dValidatePaymentSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x0ereservation_id\x18\x02 \x01(\x03B\x020\x01R\rreservationId\"6\n" +
	"\x1eValidatePaymentSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\xc9\x03\n" +
	"\x0fPaymentsService\x12j\n" +
	"\x13CreatePaymentIntent\x12(.api.payments.CreatePaymentIntentRequest\x1a).api.payments.CreatePaymentIntentResponse\x12g\n" +
	"\x12GetStripePublicKey\x12'.api.payments.GetStripePublicKeyRequest\x1a(.api.payments.GetStripePublicKeyResponse\x12l\n" +
	"\x14CreatePaymentSession\x12(.api.payments.CreatePaymentIntentRequest\x1a*.api.payments.CreatePaymentSessionResponse\x12s\n" +
	"\x16ValidatePaymentSession\x12+.api.payments.ValidatePaymentSessionRequest\x1a,.api.payments.ValidatePaymentSessionResponseB\x9f\x01\n" +
	"\x10com.api.paymentsB\rPaymentsProtoP\x01Z+api/internal/proto/payments;paymentsservice\xa2\x02\x03APX\xaa\x02\fApi.Payments\xca\x02\fApi\\Payments\xe2\x02\x18Api\\Payments\\GPBMetadata\xea\x02\rApi::Paymentsb\x06proto3"

var (
	file_proto_payments_payments_proto_rawDescOnce sync.Once
	file_proto_payments_payments_proto_rawDescData []byte
)

func file_proto_payments_payments_proto_rawDescGZIP() []byte {
	file_proto_payments_payments_proto_rawDescOnce.Do(func() {
		file_proto_payments_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payments_payments_proto_rawDesc), len(file_proto_payments_payments_proto_rawDesc)))
	})
	return file_proto_payments_payments_proto_rawDescData
}

var file_proto_payments_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_payments_payments_proto_goTypes = []any{
	(*CreatePaymentIntentRequest)(nil),     // 0: api.payments.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil),    // 1: api.payments.CreatePaymentIntentResponse
	(*GetStripePublicKeyRequest)(nil),      // 2: api.payments.GetStripePublicKeyRequest
	(*GetStripePublicKeyResponse)(nil),     // 3: api.payments.GetStripePublicKeyResponse
	(*CreatePaymentSessionResponse)(nil),   // 4: api.payments.CreatePaymentSessionResponse
	(*ValidatePaymentSessionRequest)(nil),  // 5: api.payments.ValidatePaymentSessionRequest
	(*ValidatePaymentSessionResponse)(nil), // 6: api.payments.ValidatePaymentSessionResponse
}
var file_proto_payments_payments_proto_depIdxs = []int32{
	0, // 0: api.payments.PaymentsService.CreatePaymentIntent:input_type -> api.payments.CreatePaymentIntentRequest
	2, // 1: api.payments.PaymentsService.GetStripePublicKey:input_type -> api.payments.GetStripePublicKeyRequest
	0, // 2: api.payments.PaymentsService.CreatePaymentSession:input_type -> api.payments.CreatePaymentIntentRequest
	5, // 3: api.payments.PaymentsService.ValidatePaymentSession:input_type -> api.payments.ValidatePaymentSessionRequest
	1, // 4: api.payments.PaymentsService.CreatePaymentIntent:output_type -> api.payments.CreatePaymentIntentResponse
	3, // 5: api.payments.PaymentsService.GetStripePublicKey:output_type -> api.payments.GetStripePublicKeyResponse
	4, // 6: api.payments.PaymentsService.CreatePaymentSession:output_type -> api.payments.CreatePaymentSessionResponse
	6, // 7: api.payments.PaymentsService.ValidatePaymentSession:output_type -> api.payments.ValidatePaymentSessionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payments_payments_proto_init() }
func file_proto_payments_payments_proto_init() {
	if File_proto_payments_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payments_payments_proto_rawDesc), len(file_proto_payments_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payments_payments_proto_goTypes,
		DependencyIndexes: file_proto_payments_payments_proto_depIdxs,
		MessageInfos:      file_proto_payments_payments_proto_msgTypes,
	}.Build()
	File_proto_payments_payments_proto = out.File
	file_proto_payments_payments_proto_goTypes = nil
	file_proto_payments_payments_proto_depIdxs = nil
}
