// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/facilities/facilities.proto

package facilitiesservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Facility struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImagePath        *string                `protobuf:"bytes,3,opt,name=image_path,json=imagePath,proto3,oneof" json:"image_path,omitempty"`
	Capacity         *int64                 `protobuf:"varint,4,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 string
	UpdatedAt        string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339 string
	GoogleCalendarId string                 `protobuf:"bytes,7,opt,name=google_calendar_id,json=googleCalendarId,proto3" json:"google_calendar_id,omitempty"`
	BuildingId       *int64                 `protobuf:"varint,8,opt,name=building_id,json=buildingId,proto3,oneof" json:"building_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Facility) Reset() {
	*x = Facility{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facility) ProtoMessage() {}

func (x *Facility) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facility.ProtoReflect.Descriptor instead.
func (*Facility) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{0}
}

func (x *Facility) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Facility) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Facility) GetImagePath() string {
	if x != nil && x.ImagePath != nil {
		return *x.ImagePath
	}
	return ""
}

func (x *Facility) GetCapacity() int64 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

func (x *Facility) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Facility) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Facility) GetGoogleCalendarId() string {
	if x != nil {
		return x.GoogleCalendarId
	}
	return ""
}

func (x *Facility) GetBuildingId() int64 {
	if x != nil && x.BuildingId != nil {
		return *x.BuildingId
	}
	return 0
}

type Building struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ImagePath        *string                `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3,oneof" json:"image_path,omitempty"`
	GoogleCalendarId *string                `protobuf:"bytes,5,opt,name=google_calendar_id,json=googleCalendarId,proto3,oneof" json:"google_calendar_id,omitempty"`
	Latitude         *float64               `protobuf:"fixed64,6,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude        *float64               `protobuf:"fixed64,7,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Building) Reset() {
	*x = Building{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Building) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Building) ProtoMessage() {}

func (x *Building) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Building.ProtoReflect.Descriptor instead.
func (*Building) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{1}
}

func (x *Building) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Building) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Building) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Building) GetImagePath() string {
	if x != nil && x.ImagePath != nil {
		return *x.ImagePath
	}
	return ""
}

func (x *Building) GetGoogleCalendarId() string {
	if x != nil && x.GoogleCalendarId != nil {
		return *x.GoogleCalendarId
	}
	return ""
}

func (x *Building) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Building) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type BuildingWithFacilities struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Building      *Building                 `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`
	Facilities    []*FacilityWithCategories `protobuf:"bytes,2,rep,name=facilities,proto3" json:"facilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildingWithFacilities) Reset() {
	*x = BuildingWithFacilities{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingWithFacilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingWithFacilities) ProtoMessage() {}

func (x *BuildingWithFacilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingWithFacilities.ProtoReflect.Descriptor instead.
func (*BuildingWithFacilities) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{2}
}

func (x *BuildingWithFacilities) GetBuilding() *Building {
	if x != nil {
		return x.Building
	}
	return nil
}

func (x *BuildingWithFacilities) GetFacilities() []*FacilityWithCategories {
	if x != nil {
		return x.Facilities
	}
	return nil
}

type BuildingWithEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Building      *Building              `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildingWithEvents) Reset() {
	*x = BuildingWithEvents{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingWithEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingWithEvents) ProtoMessage() {}

func (x *BuildingWithEvents) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingWithEvents.ProtoReflect.Descriptor instead.
func (*BuildingWithEvents) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{3}
}

func (x *BuildingWithEvents) GetBuilding() *Building {
	if x != nil {
		return x.Building
	}
	return nil
}

func (x *BuildingWithEvents) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	FacilityId    int64                  `protobuf:"varint,5,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{4}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Category) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

type FacilityWithCategories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *Facility              `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacilityWithCategories) Reset() {
	*x = FacilityWithCategories{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacilityWithCategories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacilityWithCategories) ProtoMessage() {}

func (x *FacilityWithCategories) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacilityWithCategories.ProtoReflect.Descriptor instead.
func (*FacilityWithCategories) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{5}
}

func (x *FacilityWithCategories) GetFacility() *Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

func (x *FacilityWithCategories) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Start         string                 `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	HtmlLink      string                 `protobuf:"bytes,7,opt,name=html_link,json=htmlLink,proto3" json:"html_link,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Event) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *Event) GetHtmlLink() string {
	if x != nil {
		return x.HtmlLink
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Coords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Building      string                 `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coords) Reset() {
	*x = Coords{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coords) ProtoMessage() {}

func (x *Coords) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coords.ProtoReflect.Descriptor instead.
func (*Coords) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{7}
}

func (x *Coords) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Coords) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *Coords) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coords) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetAllCoordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCoordsRequest) Reset() {
	*x = GetAllCoordsRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCoordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCoordsRequest) ProtoMessage() {}

func (x *GetAllCoordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCoordsRequest.ProtoReflect.Descriptor instead.
func (*GetAllCoordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{8}
}

type GetAllCoordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Coords              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCoordsResponse) Reset() {
	*x = GetAllCoordsResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCoordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCoordsResponse) ProtoMessage() {}

func (x *GetAllCoordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCoordsResponse.ProtoReflect.Descriptor instead.
func (*GetAllCoordsResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllCoordsResponse) GetData() []*Coords {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{10}
}

func (x *GetCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEventsByFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByFacilityRequest) Reset() {
	*x = GetEventsByFacilityRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByFacilityRequest) ProtoMessage() {}

func (x *GetEventsByFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByFacilityRequest.ProtoReflect.Descriptor instead.
func (*GetEventsByFacilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{11}
}

func (x *GetEventsByFacilityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEventsByFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByFacilityResponse) Reset() {
	*x = GetEventsByFacilityResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByFacilityResponse) ProtoMessage() {}

func (x *GetEventsByFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByFacilityResponse.ProtoReflect.Descriptor instead.
func (*GetEventsByFacilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{12}
}

func (x *GetEventsByFacilityResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsByBuildingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByBuildingRequest) Reset() {
	*x = GetEventsByBuildingRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByBuildingRequest) ProtoMessage() {}

func (x *GetEventsByBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByBuildingRequest.ProtoReflect.Descriptor instead.
func (*GetEventsByBuildingRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventsByBuildingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEventsByBuildingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByBuildingResponse) Reset() {
	*x = GetEventsByBuildingResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByBuildingResponse) ProtoMessage() {}

func (x *GetEventsByBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByBuildingResponse.ProtoReflect.Descriptor instead.
func (*GetEventsByBuildingResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{14}
}

func (x *GetEventsByBuildingResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetAllEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEventsRequest) Reset() {
	*x = GetAllEventsRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEventsRequest) ProtoMessage() {}

func (x *GetAllEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEventsRequest.ProtoReflect.Descriptor instead.
func (*GetAllEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{15}
}

type GetAllEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*BuildingWithEvents  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEventsResponse) Reset() {
	*x = GetAllEventsResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEventsResponse) ProtoMessage() {}

func (x *GetAllEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEventsResponse.ProtoReflect.Descriptor instead.
func (*GetAllEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllEventsResponse) GetData() []*BuildingWithEvents {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllBuildingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBuildingsRequest) Reset() {
	*x = GetAllBuildingsRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBuildingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBuildingsRequest) ProtoMessage() {}

func (x *GetAllBuildingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBuildingsRequest.ProtoReflect.Descriptor instead.
func (*GetAllBuildingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{17}
}

type GetAllBuildingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buildings     []*Building            `protobuf:"bytes,1,rep,name=buildings,proto3" json:"buildings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBuildingsResponse) Reset() {
	*x = GetAllBuildingsResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBuildingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBuildingsResponse) ProtoMessage() {}

func (x *GetAllBuildingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBuildingsResponse.ProtoReflect.Descriptor instead.
func (*GetAllBuildingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllBuildingsResponse) GetBuildings() []*Building {
	if x != nil {
		return x.Buildings
	}
	return nil
}

type GetAllFacilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFacilitiesRequest) Reset() {
	*x = GetAllFacilitiesRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFacilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFacilitiesRequest) ProtoMessage() {}

func (x *GetAllFacilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFacilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetAllFacilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{19}
}

type GetFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacilityRequest) Reset() {
	*x = GetFacilityRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacilityRequest) ProtoMessage() {}

func (x *GetFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacilityRequest.ProtoReflect.Descriptor instead.
func (*GetFacilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{20}
}

func (x *GetFacilityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFacilityCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacilityCategoriesRequest) Reset() {
	*x = GetFacilityCategoriesRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacilityCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacilityCategoriesRequest) ProtoMessage() {}

func (x *GetFacilityCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacilityCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetFacilityCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{21}
}

func (x *GetFacilityCategoriesRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBuildingFacilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildingId    int64                  `protobuf:"varint,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildingFacilitiesRequest) Reset() {
	*x = GetBuildingFacilitiesRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildingFacilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingFacilitiesRequest) ProtoMessage() {}

func (x *GetBuildingFacilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingFacilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetBuildingFacilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{22}
}

func (x *GetBuildingFacilitiesRequest) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

type GetAllFacilitiesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Buildings     []*BuildingWithFacilities `protobuf:"bytes,1,rep,name=buildings,proto3" json:"buildings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFacilitiesResponse) Reset() {
	*x = GetAllFacilitiesResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFacilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFacilitiesResponse) ProtoMessage() {}

func (x *GetAllFacilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFacilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetAllFacilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{23}
}

func (x *GetAllFacilitiesResponse) GetBuildings() []*BuildingWithFacilities {
	if x != nil {
		return x.Buildings
	}
	return nil
}

type GetFacilityCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacilityCategoriesResponse) Reset() {
	*x = GetFacilityCategoriesResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacilityCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacilityCategoriesResponse) ProtoMessage() {}

func (x *GetFacilityCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacilityCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetFacilityCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{24}
}

func (x *GetFacilityCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetBuildingFacilitiesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Building      *BuildingWithFacilities `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildingFacilitiesResponse) Reset() {
	*x = GetBuildingFacilitiesResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildingFacilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingFacilitiesResponse) ProtoMessage() {}

func (x *GetBuildingFacilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingFacilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetBuildingFacilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{25}
}

func (x *GetBuildingFacilitiesResponse) GetBuilding() *BuildingWithFacilities {
	if x != nil {
		return x.Building
	}
	return nil
}

type CreateFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *Facility              `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFacilityRequest) Reset() {
	*x = CreateFacilityRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFacilityRequest) ProtoMessage() {}

func (x *CreateFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFacilityRequest.ProtoReflect.Descriptor instead.
func (*CreateFacilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{26}
}

func (x *CreateFacilityRequest) GetFacility() *Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

func (x *CreateFacilityRequest) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type UpdateFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *Facility              `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacilityRequest) Reset() {
	*x = UpdateFacilityRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacilityRequest) ProtoMessage() {}

func (x *UpdateFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateFacilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateFacilityRequest) GetFacility() *Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

func (x *UpdateFacilityRequest) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type DeleteFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFacilityRequest) Reset() {
	*x = DeleteFacilityRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFacilityRequest) ProtoMessage() {}

func (x *DeleteFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFacilityRequest.ProtoReflect.Descriptor instead.
func (*DeleteFacilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteFacilityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFacilityResponse) Reset() {
	*x = DeleteFacilityResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFacilityResponse) ProtoMessage() {}

func (x *DeleteFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFacilityResponse.ProtoReflect.Descriptor instead.
func (*DeleteFacilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{29}
}

type UpdateFacilityCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacilityCategoryRequest) Reset() {
	*x = UpdateFacilityCategoryRequest{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacilityCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacilityCategoryRequest) ProtoMessage() {}

func (x *UpdateFacilityCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacilityCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateFacilityCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateFacilityCategoryRequest) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type CreateFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFacilityResponse) Reset() {
	*x = CreateFacilityResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFacilityResponse) ProtoMessage() {}

func (x *CreateFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFacilityResponse.ProtoReflect.Descriptor instead.
func (*CreateFacilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{31}
}

type UpdateFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacilityResponse) Reset() {
	*x = UpdateFacilityResponse{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacilityResponse) ProtoMessage() {}

func (x *UpdateFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacilityResponse.ProtoReflect.Descriptor instead.
func (*UpdateFacilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{32}
}

type FullFacility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *Facility              `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	ReservationId []int64                `protobuf:"varint,3,rep,packed,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Building      *Building              `protobuf:"bytes,4,opt,name=building,proto3" json:"building,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullFacility) Reset() {
	*x = FullFacility{}
	mi := &file_proto_facilities_facilities_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullFacility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullFacility) ProtoMessage() {}

func (x *FullFacility) ProtoReflect() protoreflect.Message {
	mi := &file_proto_facilities_facilities_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullFacility.ProtoReflect.Descriptor instead.
func (*FullFacility) Descriptor() ([]byte, []int) {
	return file_proto_facilities_facilities_proto_rawDescGZIP(), []int{33}
}

func (x *FullFacility) GetFacility() *Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

func (x *FullFacility) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *FullFacility) GetReservationId() []int64 {
	if x != nil {
		return x.ReservationId
	}
	return nil
}

func (x *FullFacility) GetBuilding() *Building {
	if x != nil {
		return x.Building
	}
	return nil
}

var File_proto_facilities_facilities_proto protoreflect.FileDescriptor

const file_proto_facilities_facilities_proto_rawDesc = "" +
	"\n" +
	"!proto/facilities/facilities.proto\x12\x0eapi.facilities\"\xbd\x02\n" +
	"\bFacility\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"image_path\x18\x03 \x01(\tH\x00R\timagePath\x88\x01\x01\x12#\n" +
	"\bcapacity\x18\x04 \x01(\x03B\x020\x01H\x01R\bcapacity\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12,\n" +
	"\x12google_calendar_id\x18\a \x01(\tR\x10googleCalendarId\x12(\n" +
	"\vbuilding_id\x18\b \x01(\x03B\x020\x01H\x02R\n" +
	"buildingId\x88\x01\x01B\r\n" +
	"\v_image_pathB\v\n" +
	"\t_capacityB\x0e\n" +
	"\f_building_id\"\xa8\x02\n" +
	"\bBuilding\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\"\n" +
	"\n" +
	"image_path\x18\x04 \x01(\tH\x00R\timagePath\x88\x01\x01\x121\n" +
	"\x12google_calendar_id\x18\x05 \x01(\tH\x01R\x10googleCalendarId\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\x06 \x01(\x01H\x02R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\a \x01(\x01H\x03R\tlongitude\x88\x01\x01B\r\n" +
	"\v_image_pathB\x15\n" +
	"\x13_google_calendar_idB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"\x96\x01\n" +
	"\x16BuildingWithFacilities\x124\n" +
	"\bbuilding\x18\x01 \x01(\v2\x18.api.facilities.BuildingR\bbuilding\x12F\n" +
	"\n" +
	"facilities\x18\x02 \x03(\v2&.api.facilities.FacilityWithCategoriesR\n" +
	"facilities\"y\n" +
	"\x12BuildingWithEvents\x124\n" +
	"\bbuilding\x18\x01 \x01(\v2\x18.api.facilities.BuildingR\bbuilding\x12-\n" +
	"\x06events\x18\x02 \x03(\v2\x15.api.facilities.EventR\x06events\"\x8f\x01\n" +
	"\bCategory\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12#\n" +
	"\vfacility_id\x18\x05 \x01(\x03B\x020\x01R\n" +
	"facilityId\"\x88\x01\n" +
	"\x16FacilityWithCategories\x124\n" +
	"\bfacility\x18\x01 \x01(\v2\x18.api.facilities.FacilityR\bfacility\x128\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x18.api.facilities.CategoryR\n" +
	"categories\"\xba\x01\n" +
	"\x05Event\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05start\x18\x04 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x05 \x01(\tR\x03end\x12\x1b\n" +
	"\thtml_link\x18\a \x01(\tR\bhtmlLink\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\"r\n" +
	"\x06coords\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\x12\x1a\n" +
	"\bbuilding\x18\x02 \x01(\tR\bbuilding\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"\x15\n" +
	"\x13GetAllCoordsRequest\"B\n" +
	"\x14GetAllCoordsResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.api.facilities.coordsR\x04data\"(\n" +
	"\x12GetCategoryRequest\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\"0\n" +
	"\x1aGetEventsByFacilityRequest\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\"L\n" +
	"\x1bGetEventsByFacilityResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.api.facilities.EventR\x06events\"0\n" +
	"\x1aGetEventsByBuildingRequest\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\"L\n" +
	"\x1bGetEventsByBuildingResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.api.facilities.EventR\x06events\"\x15\n" +
	"\x13GetAllEventsRequest\"N\n" +
	"\x14GetAllEventsResponse\x126\n" +
	"\x04data\x18\x01 \x03(\v2\".api.facilities.BuildingWithEventsR\x04data\"\x18\n" +
	"\x16GetAllBuildingsRequest\"Q\n" +
	"\x17GetAllBuildingsResponse\x126\n" +
	"\tbuildings\x18\x01 \x03(\v2\x18.api.facilities.BuildingR\tbuildings\"\x19\n" +
	"\x17GetAllFacilitiesRequest\"(\n" +
	"\x12GetFacilityRequest\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\"2\n" +
	"\x1cGetFacilityCategoriesRequest\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\"C\n" +
	"\x1cGetBuildingFacilitiesRequest\x12#\n" +
	"\vbuilding_id\x18\x01 \x01(\x03B\x020\x01R\n" +
	"buildingId\"`\n" +
	"\x18GetAllFacilitiesResponse\x12D\n" +
	"\tbuildings\x18\x01 \x03(\v2&.api.facilities.BuildingWithFacilitiesR\tbuildings\"Y\n" +
	"\x1dGetFacilityCategoriesResponse\x128\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x18.api.facilities.CategoryR\n" +
	"categories\"c\n" +
	"\x1dGetBuildingFacilitiesResponse\x12B\n" +
	"\bbuilding\x18\x01 \x01(\v2&.api.facilities.BuildingWithFacilitiesR\bbuilding\"\x87\x01\n" +
	"\x15CreateFacilityRequest\x124\n" +
	"\bfacility\x18\x01 \x01(\v2\x18.api.facilities.FacilityR\bfacility\x128\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x18.api.facilities.CategoryR\n" +
	"categories\"\x87\x01\n" +
	"\x15UpdateFacilityRequest\x124\n" +
	"\bfacility\x18\x01 \x01(\v2\x18.api.facilities.FacilityR\bfacility\x128\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x18.api.facilities.CategoryR\n" +
	"categories\"+\n" +
	"\x15DeleteFacilityRequest\x12\x12\n" +
	"\x02id\x18\x01 \x01(\x03B\x020\x01R\x02id\"\x18\n" +
	"\x16DeleteFacilityResponse\"U\n" +
	"\x1dUpdateFacilityCategoryRequest\x124\n" +
	"\bcategory\x18\x01 \x01(\v2\x18.api.facilities.CategoryR\bcategory\"\x18\n" +
	"\x16CreateFacilityResponse\"\x18\n" +
	"\x16UpdateFacilityResponse\"\xdf\x01\n" +
	"\fFullFacility\x124\n" +
	"\bfacility\x18\x01 \x01(\v2\x18.api.facilities.FacilityR\bfacility\x128\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x18.api.facilities.CategoryR\n" +
	"categories\x12)\n" +
	"\x0ereservation_id\x18\x03 \x03(\x03B\x020\x01R\rreservationId\x124\n" +
	"\bbuilding\x18\x04 \x01(\v2\x18.api.facilities.BuildingR\bbuilding2\xb6\v\n" +
	"\x11FacilitiesService\x12j\n" +
	"\x10GetAllFacilities\x12'.api.facilities.GetAllFacilitiesRequest\x1a(.api.facilities.GetAllFacilitiesResponse\"\x03\x90\x02\x01\x12g\n" +
	"\x0fGetAllBuildings\x12&.api.facilities.GetAllBuildingsRequest\x1a'.api.facilities.GetAllBuildingsResponse\"\x03\x90\x02\x01\x12T\n" +
	"\vGetFacility\x12\".api.facilities.GetFacilityRequest\x1a\x1c.api.facilities.FullFacility\"\x03\x90\x02\x01\x12s\n" +
	"\x13GetEventsByFacility\x12*.api.facilities.GetEventsByFacilityRequest\x1a+.api.facilities.GetEventsByFacilityResponse\"\x03\x90\x02\x01\x12s\n" +
	"\x13GetEventsByBuilding\x12*.api.facilities.GetEventsByBuildingRequest\x1a+.api.facilities.GetEventsByBuildingResponse\"\x03\x90\x02\x01\x12^\n" +
	"\fGetAllEvents\x12#.api.facilities.GetAllEventsRequest\x1a$.api.facilities.GetAllEventsResponse\"\x03\x90\x02\x01\x12y\n" +
	"\x15GetFacilityCategories\x12,.api.facilities.GetFacilityCategoriesRequest\x1a-.api.facilities.GetFacilityCategoriesResponse\"\x03\x90\x02\x01\x12y\n" +
	"\x15GetBuildingFacilities\x12,.api.facilities.GetBuildingFacilitiesRequest\x1a-.api.facilities.GetBuildingFacilitiesResponse\"\x03\x90\x02\x01\x12_\n" +
	"\x0eCreateFacility\x12%.api.facilities.CreateFacilityRequest\x1a&.api.facilities.CreateFacilityResponse\x12_\n" +
	"\x0eUpdateFacility\x12%.api.facilities.UpdateFacilityRequest\x1a&.api.facilities.UpdateFacilityResponse\x12_\n" +
	"\x0eDeleteFacility\x12%.api.facilities.DeleteFacilityRequest\x1a&.api.facilities.DeleteFacilityResponse\x12a\n" +
	"\x16UpdateFacilityCategory\x12-.api.facilities.UpdateFacilityCategoryRequest\x1a\x18.api.facilities.Category\x12P\n" +
	"\vGetCategory\x12\".api.facilities.GetCategoryRequest\x1a\x18.api.facilities.Category\"\x03\x90\x02\x01\x12^\n" +
	"\fGetAllCoords\x12#.api.facilities.GetAllCoordsRequest\x1a$.api.facilities.GetAllCoordsResponse\"\x03\x90\x02\x01B\xaf\x01\n" +
	"\x12com.api.facilitiesB\x0fFacilitiesProtoP\x01Z/api/internal/proto/facilities;facilitiesservice\xa2\x02\x03AFX\xaa\x02\x0eApi.Facilities\xca\x02\x0eApi\\Facilities\xe2\x02\x1aApi\\Facilities\\GPBMetadata\xea\x02\x0fApi::Facilitiesb\x06proto3"

var (
	file_proto_facilities_facilities_proto_rawDescOnce sync.Once
	file_proto_facilities_facilities_proto_rawDescData []byte
)

func file_proto_facilities_facilities_proto_rawDescGZIP() []byte {
	file_proto_facilities_facilities_proto_rawDescOnce.Do(func() {
		file_proto_facilities_facilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_facilities_facilities_proto_rawDesc), len(file_proto_facilities_facilities_proto_rawDesc)))
	})
	return file_proto_facilities_facilities_proto_rawDescData
}

var file_proto_facilities_facilities_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_facilities_facilities_proto_goTypes = []any{
	(*Facility)(nil),                      // 0: api.facilities.Facility
	(*Building)(nil),                      // 1: api.facilities.Building
	(*BuildingWithFacilities)(nil),        // 2: api.facilities.BuildingWithFacilities
	(*BuildingWithEvents)(nil),            // 3: api.facilities.BuildingWithEvents
	(*Category)(nil),                      // 4: api.facilities.Category
	(*FacilityWithCategories)(nil),        // 5: api.facilities.FacilityWithCategories
	(*Event)(nil),                         // 6: api.facilities.Event
	(*Coords)(nil),                        // 7: api.facilities.coords
	(*GetAllCoordsRequest)(nil),           // 8: api.facilities.GetAllCoordsRequest
	(*GetAllCoordsResponse)(nil),          // 9: api.facilities.GetAllCoordsResponse
	(*GetCategoryRequest)(nil),            // 10: api.facilities.GetCategoryRequest
	(*GetEventsByFacilityRequest)(nil),    // 11: api.facilities.GetEventsByFacilityRequest
	(*GetEventsByFacilityResponse)(nil),   // 12: api.facilities.GetEventsByFacilityResponse
	(*GetEventsByBuildingRequest)(nil),    // 13: api.facilities.GetEventsByBuildingRequest
	(*GetEventsByBuildingResponse)(nil),   // 14: api.facilities.GetEventsByBuildingResponse
	(*GetAllEventsRequest)(nil),           // 15: api.facilities.GetAllEventsRequest
	(*GetAllEventsResponse)(nil),          // 16: api.facilities.GetAllEventsResponse
	(*GetAllBuildingsRequest)(nil),        // 17: api.facilities.GetAllBuildingsRequest
	(*GetAllBuildingsResponse)(nil),       // 18: api.facilities.GetAllBuildingsResponse
	(*GetAllFacilitiesRequest)(nil),       // 19: api.facilities.GetAllFacilitiesRequest
	(*GetFacilityRequest)(nil),            // 20: api.facilities.GetFacilityRequest
	(*GetFacilityCategoriesRequest)(nil),  // 21: api.facilities.GetFacilityCategoriesRequest
	(*GetBuildingFacilitiesRequest)(nil),  // 22: api.facilities.GetBuildingFacilitiesRequest
	(*GetAllFacilitiesResponse)(nil),      // 23: api.facilities.GetAllFacilitiesResponse
	(*GetFacilityCategoriesResponse)(nil), // 24: api.facilities.GetFacilityCategoriesResponse
	(*GetBuildingFacilitiesResponse)(nil), // 25: api.facilities.GetBuildingFacilitiesResponse
	(*CreateFacilityRequest)(nil),         // 26: api.facilities.CreateFacilityRequest
	(*UpdateFacilityRequest)(nil),         // 27: api.facilities.UpdateFacilityRequest
	(*DeleteFacilityRequest)(nil),         // 28: api.facilities.DeleteFacilityRequest
	(*DeleteFacilityResponse)(nil),        // 29: api.facilities.DeleteFacilityResponse
	(*UpdateFacilityCategoryRequest)(nil), // 30: api.facilities.UpdateFacilityCategoryRequest
	(*CreateFacilityResponse)(nil),        // 31: api.facilities.CreateFacilityResponse
	(*UpdateFacilityResponse)(nil),        // 32: api.facilities.UpdateFacilityResponse
	(*FullFacility)(nil),                  // 33: api.facilities.FullFacility
}
var file_proto_facilities_facilities_proto_depIdxs = []int32{
	1,  // 0: api.facilities.BuildingWithFacilities.building:type_name -> api.facilities.Building
	5,  // 1: api.facilities.BuildingWithFacilities.facilities:type_name -> api.facilities.FacilityWithCategories
	1,  // 2: api.facilities.BuildingWithEvents.building:type_name -> api.facilities.Building
	6,  // 3: api.facilities.BuildingWithEvents.events:type_name -> api.facilities.Event
	0,  // 4: api.facilities.FacilityWithCategories.facility:type_name -> api.facilities.Facility
	4,  // 5: api.facilities.FacilityWithCategories.categories:type_name -> api.facilities.Category
	7,  // 6: api.facilities.GetAllCoordsResponse.data:type_name -> api.facilities.coords
	6,  // 7: api.facilities.GetEventsByFacilityResponse.events:type_name -> api.facilities.Event
	6,  // 8: api.facilities.GetEventsByBuildingResponse.events:type_name -> api.facilities.Event
	3,  // 9: api.facilities.GetAllEventsResponse.data:type_name -> api.facilities.BuildingWithEvents
	1,  // 10: api.facilities.GetAllBuildingsResponse.buildings:type_name -> api.facilities.Building
	2,  // 11: api.facilities.GetAllFacilitiesResponse.buildings:type_name -> api.facilities.BuildingWithFacilities
	4,  // 12: api.facilities.GetFacilityCategoriesResponse.categories:type_name -> api.facilities.Category
	2,  // 13: api.facilities.GetBuildingFacilitiesResponse.building:type_name -> api.facilities.BuildingWithFacilities
	0,  // 14: api.facilities.CreateFacilityRequest.facility:type_name -> api.facilities.Facility
	4,  // 15: api.facilities.CreateFacilityRequest.categories:type_name -> api.facilities.Category
	0,  // 16: api.facilities.UpdateFacilityRequest.facility:type_name -> api.facilities.Facility
	4,  // 17: api.facilities.UpdateFacilityRequest.categories:type_name -> api.facilities.Category
	4,  // 18: api.facilities.UpdateFacilityCategoryRequest.category:type_name -> api.facilities.Category
	0,  // 19: api.facilities.FullFacility.facility:type_name -> api.facilities.Facility
	4,  // 20: api.facilities.FullFacility.categories:type_name -> api.facilities.Category
	1,  // 21: api.facilities.FullFacility.building:type_name -> api.facilities.Building
	19, // 22: api.facilities.FacilitiesService.GetAllFacilities:input_type -> api.facilities.GetAllFacilitiesRequest
	17, // 23: api.facilities.FacilitiesService.GetAllBuildings:input_type -> api.facilities.GetAllBuildingsRequest
	20, // 24: api.facilities.FacilitiesService.GetFacility:input_type -> api.facilities.GetFacilityRequest
	11, // 25: api.facilities.FacilitiesService.GetEventsByFacility:input_type -> api.facilities.GetEventsByFacilityRequest
	13, // 26: api.facilities.FacilitiesService.GetEventsByBuilding:input_type -> api.facilities.GetEventsByBuildingRequest
	15, // 27: api.facilities.FacilitiesService.GetAllEvents:input_type -> api.facilities.GetAllEventsRequest
	21, // 28: api.facilities.FacilitiesService.GetFacilityCategories:input_type -> api.facilities.GetFacilityCategoriesRequest
	22, // 29: api.facilities.FacilitiesService.GetBuildingFacilities:input_type -> api.facilities.GetBuildingFacilitiesRequest
	26, // 30: api.facilities.FacilitiesService.CreateFacility:input_type -> api.facilities.CreateFacilityRequest
	27, // 31: api.facilities.FacilitiesService.UpdateFacility:input_type -> api.facilities.UpdateFacilityRequest
	28, // 32: api.facilities.FacilitiesService.DeleteFacility:input_type -> api.facilities.DeleteFacilityRequest
	30, // 33: api.facilities.FacilitiesService.UpdateFacilityCategory:input_type -> api.facilities.UpdateFacilityCategoryRequest
	10, // 34: api.facilities.FacilitiesService.GetCategory:input_type -> api.facilities.GetCategoryRequest
	8,  // 35: api.facilities.FacilitiesService.GetAllCoords:input_type -> api.facilities.GetAllCoordsRequest
	23, // 36: api.facilities.FacilitiesService.GetAllFacilities:output_type -> api.facilities.GetAllFacilitiesResponse
	18, // 37: api.facilities.FacilitiesService.GetAllBuildings:output_type -> api.facilities.GetAllBuildingsResponse
	33, // 38: api.facilities.FacilitiesService.GetFacility:output_type -> api.facilities.FullFacility
	12, // 39: api.facilities.FacilitiesService.GetEventsByFacility:output_type -> api.facilities.GetEventsByFacilityResponse
	14, // 40: api.facilities.FacilitiesService.GetEventsByBuilding:output_type -> api.facilities.GetEventsByBuildingResponse
	16, // 41: api.facilities.FacilitiesService.GetAllEvents:output_type -> api.facilities.GetAllEventsResponse
	24, // 42: api.facilities.FacilitiesService.GetFacilityCategories:output_type -> api.facilities.GetFacilityCategoriesResponse
	25, // 43: api.facilities.FacilitiesService.GetBuildingFacilities:output_type -> api.facilities.GetBuildingFacilitiesResponse
	31, // 44: api.facilities.FacilitiesService.CreateFacility:output_type -> api.facilities.CreateFacilityResponse
	32, // 45: api.facilities.FacilitiesService.UpdateFacility:output_type -> api.facilities.UpdateFacilityResponse
	29, // 46: api.facilities.FacilitiesService.DeleteFacility:output_type -> api.facilities.DeleteFacilityResponse
	4,  // 47: api.facilities.FacilitiesService.UpdateFacilityCategory:output_type -> api.facilities.Category
	4,  // 48: api.facilities.FacilitiesService.GetCategory:output_type -> api.facilities.Category
	9,  // 49: api.facilities.FacilitiesService.GetAllCoords:output_type -> api.facilities.GetAllCoordsResponse
	36, // [36:50] is the sub-list for method output_type
	22, // [22:36] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_facilities_facilities_proto_init() }
func file_proto_facilities_facilities_proto_init() {
	if File_proto_facilities_facilities_proto != nil {
		return
	}
	file_proto_facilities_facilities_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_facilities_facilities_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_facilities_facilities_proto_rawDesc), len(file_proto_facilities_facilities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_facilities_facilities_proto_goTypes,
		DependencyIndexes: file_proto_facilities_facilities_proto_depIdxs,
		MessageInfos:      file_proto_facilities_facilities_proto_msgTypes,
	}.Build()
	File_proto_facilities_facilities_proto = out.File
	file_proto_facilities_facilities_proto_goTypes = nil
	file_proto_facilities_facilities_proto_depIdxs = nil
}
