// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/reservation/reservation.proto

package reservationservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventName     string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	FacilityId    int64                  `protobuf:"varint,4,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Approved      string                 `protobuf:"bytes,5,opt,name=approved,proto3" json:"approved,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Details       *string                `protobuf:"bytes,8,opt,name=details,proto3,oneof" json:"details,omitempty"`
	Fees          string                 `protobuf:"bytes,9,opt,name=fees,proto3" json:"fees,omitempty"` // pgtype.Numeric as string
	Insurance     bool                   `protobuf:"varint,10,opt,name=insurance,proto3" json:"insurance,omitempty"`
	DoorAccess    *bool                  `protobuf:"varint,11,opt,name=door_access,json=doorAccess,proto3,oneof" json:"door_access,omitempty"`
	DoorsDetails  *string                `protobuf:"bytes,12,opt,name=doors_details,json=doorsDetails,proto3,oneof" json:"doors_details,omitempty"`
	Name          *string                `protobuf:"bytes,13,opt,name=name,proto3,oneof" json:"name,omitempty"`
	TechDetails   *string                `protobuf:"bytes,14,opt,name=tech_details,json=techDetails,proto3,oneof" json:"tech_details,omitempty"`
	TechSupport   *bool                  `protobuf:"varint,15,opt,name=tech_support,json=techSupport,proto3,oneof" json:"tech_support,omitempty"`
	Phone         *string                `protobuf:"bytes,16,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	CategoryId    int64                  `protobuf:"varint,17,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TotalHours    *float64               `protobuf:"fixed64,18,opt,name=total_hours,json=totalHours,proto3,oneof" json:"total_hours,omitempty"`
	InPerson      bool                   `protobuf:"varint,19,opt,name=in_person,json=inPerson,proto3" json:"in_person,omitempty"`
	Paid          bool                   `protobuf:"varint,20,opt,name=paid,proto3" json:"paid,omitempty"`
	PaymentUrl    *string                `protobuf:"bytes,21,opt,name=payment_url,json=paymentUrl,proto3,oneof" json:"payment_url,omitempty"`
	PaymentLinkId *string                `protobuf:"bytes,22,opt,name=payment_link_id,json=paymentLinkId,proto3,oneof" json:"payment_link_id,omitempty"`
	InsuranceLink *string                `protobuf:"bytes,23,opt,name=insurance_link,json=insuranceLink,proto3,oneof" json:"insurance_link,omitempty"`
	CostOverride  string                 `protobuf:"bytes,24,opt,name=cost_override,json=costOverride,proto3" json:"cost_override,omitempty"` // pgtype.Numeric as string
	Rrule         *string                `protobuf:"bytes,25,opt,name=rrule,proto3,oneof" json:"rrule,omitempty"`
	Rdates        []string               `protobuf:"bytes,26,rep,name=rdates,proto3" json:"rdates,omitempty"`
	Exdates       []string               `protobuf:"bytes,27,rep,name=exdates,proto3" json:"exdates,omitempty"`
	GcalEventid   *string                `protobuf:"bytes,28,opt,name=gcal_eventid,json=gcalEventid,proto3,oneof" json:"gcal_eventid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *Reservation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reservation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reservation) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Reservation) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

func (x *Reservation) GetApproved() string {
	if x != nil {
		return x.Approved
	}
	return ""
}

func (x *Reservation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Reservation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Reservation) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

func (x *Reservation) GetFees() string {
	if x != nil {
		return x.Fees
	}
	return ""
}

func (x *Reservation) GetInsurance() bool {
	if x != nil {
		return x.Insurance
	}
	return false
}

func (x *Reservation) GetDoorAccess() bool {
	if x != nil && x.DoorAccess != nil {
		return *x.DoorAccess
	}
	return false
}

func (x *Reservation) GetDoorsDetails() string {
	if x != nil && x.DoorsDetails != nil {
		return *x.DoorsDetails
	}
	return ""
}

func (x *Reservation) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Reservation) GetTechDetails() string {
	if x != nil && x.TechDetails != nil {
		return *x.TechDetails
	}
	return ""
}

func (x *Reservation) GetTechSupport() bool {
	if x != nil && x.TechSupport != nil {
		return *x.TechSupport
	}
	return false
}

func (x *Reservation) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Reservation) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Reservation) GetTotalHours() float64 {
	if x != nil && x.TotalHours != nil {
		return *x.TotalHours
	}
	return 0
}

func (x *Reservation) GetInPerson() bool {
	if x != nil {
		return x.InPerson
	}
	return false
}

func (x *Reservation) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *Reservation) GetPaymentUrl() string {
	if x != nil && x.PaymentUrl != nil {
		return *x.PaymentUrl
	}
	return ""
}

func (x *Reservation) GetPaymentLinkId() string {
	if x != nil && x.PaymentLinkId != nil {
		return *x.PaymentLinkId
	}
	return ""
}

func (x *Reservation) GetInsuranceLink() string {
	if x != nil && x.InsuranceLink != nil {
		return *x.InsuranceLink
	}
	return ""
}

func (x *Reservation) GetCostOverride() string {
	if x != nil {
		return x.CostOverride
	}
	return ""
}

func (x *Reservation) GetRrule() string {
	if x != nil && x.Rrule != nil {
		return *x.Rrule
	}
	return ""
}

func (x *Reservation) GetRdates() []string {
	if x != nil {
		return x.Rdates
	}
	return nil
}

func (x *Reservation) GetExdates() []string {
	if x != nil {
		return x.Exdates
	}
	return nil
}

func (x *Reservation) GetGcalEventid() string {
	if x != nil && x.GcalEventid != nil {
		return *x.GcalEventid
	}
	return ""
}

type ReservationDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReservationId int64                  `protobuf:"varint,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Approved      string                 `protobuf:"bytes,3,opt,name=approved,proto3" json:"approved,omitempty"`
	GcalEventid   *string                `protobuf:"bytes,4,opt,name=gcal_eventid,json=gcalEventid,proto3,oneof" json:"gcal_eventid,omitempty"`
	LocalStart    string                 `protobuf:"bytes,5,opt,name=local_start,json=localStart,proto3" json:"local_start,omitempty"`
	LocalEnd      string                 `protobuf:"bytes,6,opt,name=local_end,json=localEnd,proto3" json:"local_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationDate) Reset() {
	*x = ReservationDate{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationDate) ProtoMessage() {}

func (x *ReservationDate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationDate.ProtoReflect.Descriptor instead.
func (*ReservationDate) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *ReservationDate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReservationDate) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *ReservationDate) GetApproved() string {
	if x != nil {
		return x.Approved
	}
	return ""
}

func (x *ReservationDate) GetGcalEventid() string {
	if x != nil && x.GcalEventid != nil {
		return *x.GcalEventid
	}
	return ""
}

func (x *ReservationDate) GetLocalStart() string {
	if x != nil {
		return x.LocalStart
	}
	return ""
}

func (x *ReservationDate) GetLocalEnd() string {
	if x != nil {
		return x.LocalEnd
	}
	return ""
}

type RecurrencePattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Freq          string                 `protobuf:"bytes,1,opt,name=freq,proto3" json:"freq,omitempty"`
	ByWeekday     []string               `protobuf:"bytes,2,rep,name=by_weekday,json=byWeekday,proto3" json:"by_weekday,omitempty"`
	Until         string                 `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecurrencePattern) Reset() {
	*x = RecurrencePattern{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecurrencePattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecurrencePattern) ProtoMessage() {}

func (x *RecurrencePattern) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecurrencePattern.ProtoReflect.Descriptor instead.
func (*RecurrencePattern) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *RecurrencePattern) GetFreq() string {
	if x != nil {
		return x.Freq
	}
	return ""
}

func (x *RecurrencePattern) GetByWeekday() []string {
	if x != nil {
		return x.ByWeekday
	}
	return nil
}

func (x *RecurrencePattern) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *RecurrencePattern) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Occurrence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"` // "YYYY-MM-DDTHH:mm"
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`     // "YYYY-MM-DDTHH:mm"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Occurrence) Reset() {
	*x = Occurrence{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Occurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Occurrence) ProtoMessage() {}

func (x *Occurrence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Occurrence.ProtoReflect.Descriptor instead.
func (*Occurrence) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *Occurrence) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Occurrence) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type ReservationFee struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AdditionalFees string                 `protobuf:"bytes,2,opt,name=additional_fees,json=additionalFees,proto3" json:"additional_fees,omitempty"` // pgtype.Numeric as string
	FeesType       *string                `protobuf:"bytes,3,opt,name=fees_type,json=feesType,proto3,oneof" json:"fees_type,omitempty"`
	ReservationId  int64                  `protobuf:"varint,4,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReservationFee) Reset() {
	*x = ReservationFee{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationFee) ProtoMessage() {}

func (x *ReservationFee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationFee.ProtoReflect.Descriptor instead.
func (*ReservationFee) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *ReservationFee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReservationFee) GetAdditionalFees() string {
	if x != nil {
		return x.AdditionalFees
	}
	return ""
}

func (x *ReservationFee) GetFeesType() string {
	if x != nil && x.FeesType != nil {
		return *x.FeesType
	}
	return ""
}

func (x *ReservationFee) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

type FullReservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Dates         []*ReservationDate     `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`
	Fees          []*ReservationFee      `protobuf:"bytes,3,rep,name=fees,proto3" json:"fees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullReservation) Reset() {
	*x = FullReservation{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullReservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullReservation) ProtoMessage() {}

func (x *FullReservation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullReservation.ProtoReflect.Descriptor instead.
func (*FullReservation) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *FullReservation) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

func (x *FullReservation) GetDates() []*ReservationDate {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *FullReservation) GetFees() []*ReservationFee {
	if x != nil {
		return x.Fees
	}
	return nil
}

type FullResWithFacilityName struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventName       string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	FacilityName    string                 `protobuf:"bytes,2,opt,name=facility_name,json=facilityName,proto3" json:"facility_name,omitempty"`
	ReservationDate string                 `protobuf:"bytes,3,opt,name=reservation_date,json=reservationDate,proto3" json:"reservation_date,omitempty"`
	Approved        string                 `protobuf:"bytes,4,opt,name=approved,proto3" json:"approved,omitempty"`
	UserName        string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ResrervationId  int64                  `protobuf:"varint,6,opt,name=resrervation_id,json=resrervationId,proto3" json:"resrervation_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FullResWithFacilityName) Reset() {
	*x = FullResWithFacilityName{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullResWithFacilityName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullResWithFacilityName) ProtoMessage() {}

func (x *FullResWithFacilityName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullResWithFacilityName.ProtoReflect.Descriptor instead.
func (*FullResWithFacilityName) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *FullResWithFacilityName) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *FullResWithFacilityName) GetFacilityName() string {
	if x != nil {
		return x.FacilityName
	}
	return ""
}

func (x *FullResWithFacilityName) GetReservationDate() string {
	if x != nil {
		return x.ReservationDate
	}
	return ""
}

func (x *FullResWithFacilityName) GetApproved() string {
	if x != nil {
		return x.Approved
	}
	return ""
}

func (x *FullResWithFacilityName) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *FullResWithFacilityName) GetResrervationId() int64 {
	if x != nil {
		return x.ResrervationId
	}
	return 0
}

type AllPendingResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*FullResWithFacilityName `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllPendingResponse) Reset() {
	*x = AllPendingResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPendingResponse) ProtoMessage() {}

func (x *AllPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPendingResponse.ProtoReflect.Descriptor instead.
func (*AllPendingResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *AllPendingResponse) GetData() []*FullResWithFacilityName {
	if x != nil {
		return x.Data
	}
	return nil
}

type AllSortedResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Past          []*FullResWithFacilityName `protobuf:"bytes,1,rep,name=past,proto3" json:"past,omitempty"`
	Future        []*FullResWithFacilityName `protobuf:"bytes,2,rep,name=future,proto3" json:"future,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllSortedResponse) Reset() {
	*x = AllSortedResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllSortedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllSortedResponse) ProtoMessage() {}

func (x *AllSortedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllSortedResponse.ProtoReflect.Descriptor instead.
func (*AllSortedResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *AllSortedResponse) GetPast() []*FullResWithFacilityName {
	if x != nil {
		return x.Past
	}
	return nil
}

func (x *AllSortedResponse) GetFuture() []*FullResWithFacilityName {
	if x != nil {
		return x.Future
	}
	return nil
}

type UpdateReservationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationStatusRequest) Reset() {
	*x = UpdateReservationStatusRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationStatusRequest) ProtoMessage() {}

func (x *UpdateReservationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateReservationStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateReservationStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateReservationStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateReservationDatesStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationDatesStatusRequest) Reset() {
	*x = UpdateReservationDatesStatusRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationDatesStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationDatesStatusRequest) ProtoMessage() {}

func (x *UpdateReservationDatesStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationDatesStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateReservationDatesStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateReservationDatesStatusRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateReservationDatesStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateReservationDatesStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationDatesStatusResponse) Reset() {
	*x = UpdateReservationDatesStatusResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationDatesStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationDatesStatusResponse) ProtoMessage() {}

func (x *UpdateReservationDatesStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationDatesStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateReservationDatesStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{11}
}

type AllReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*FullReservation     `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllReservationsResponse) Reset() {
	*x = AllReservationsResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReservationsResponse) ProtoMessage() {}

func (x *AllReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReservationsResponse.ProtoReflect.Descriptor instead.
func (*AllReservationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{12}
}

func (x *AllReservationsResponse) GetReservations() []*FullReservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type RequestThisWeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*FullReservation     `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestThisWeekResponse) Reset() {
	*x = RequestThisWeekResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestThisWeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestThisWeekResponse) ProtoMessage() {}

func (x *RequestThisWeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestThisWeekResponse.ProtoReflect.Descriptor instead.
func (*RequestThisWeekResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{13}
}

func (x *RequestThisWeekResponse) GetReservations() []*FullReservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type ApprovedReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*FullReservation     `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovedReservationsResponse) Reset() {
	*x = ApprovedReservationsResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovedReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovedReservationsResponse) ProtoMessage() {}

func (x *ApprovedReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovedReservationsResponse.ProtoReflect.Descriptor instead.
func (*ApprovedReservationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{14}
}

func (x *ApprovedReservationsResponse) GetReservations() []*FullReservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type PendingReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*FullReservation     `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingReservationsResponse) Reset() {
	*x = PendingReservationsResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingReservationsResponse) ProtoMessage() {}

func (x *PendingReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingReservationsResponse.ProtoReflect.Descriptor instead.
func (*PendingReservationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{15}
}

func (x *PendingReservationsResponse) GetReservations() []*FullReservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type UserReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*FullReservation     `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReservationsResponse) Reset() {
	*x = UserReservationsResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReservationsResponse) ProtoMessage() {}

func (x *UserReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReservationsResponse.ProtoReflect.Descriptor instead.
func (*UserReservationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{16}
}

func (x *UserReservationsResponse) GetReservations() []*FullReservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type GetAllReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReservationsRequest) Reset() {
	*x = GetAllReservationsRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReservationsRequest) ProtoMessage() {}

func (x *GetAllReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReservationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllReservationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{17}
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{18}
}

func (x *GetReservationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCountRequest) Reset() {
	*x = RequestCountRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCountRequest) ProtoMessage() {}

func (x *RequestCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCountRequest.ProtoReflect.Descriptor instead.
func (*RequestCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{19}
}

type RequestCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCountResponse) Reset() {
	*x = RequestCountResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCountResponse) ProtoMessage() {}

func (x *RequestCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCountResponse.ProtoReflect.Descriptor instead.
func (*RequestCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{20}
}

func (x *RequestCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRequestsThisWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestsThisWeekRequest) Reset() {
	*x = GetRequestsThisWeekRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestsThisWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestsThisWeekRequest) ProtoMessage() {}

func (x *GetRequestsThisWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestsThisWeekRequest.ProtoReflect.Descriptor instead.
func (*GetRequestsThisWeekRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{21}
}

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	FacilityId    int64                  `protobuf:"varint,3,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	TechSupport   bool                   `protobuf:"varint,8,opt,name=tech_support,json=techSupport,proto3" json:"tech_support,omitempty"`
	TechDetails   *string                `protobuf:"bytes,9,opt,name=tech_details,json=techDetails,proto3,oneof" json:"tech_details,omitempty"`
	DoorAccess    bool                   `protobuf:"varint,10,opt,name=door_access,json=doorAccess,proto3" json:"door_access,omitempty"`
	DoorsDetails  *string                `protobuf:"bytes,11,opt,name=doors_details,json=doorsDetails,proto3,oneof" json:"doors_details,omitempty"`
	Occurrences   []*Occurrence          `protobuf:"bytes,12,rep,name=occurrences,proto3" json:"occurrences,omitempty"`
	StartDate     string                 `protobuf:"bytes,13,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	StartTime     string                 `protobuf:"bytes,14,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndDate       string                 `protobuf:"bytes,15,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	EndTime       string                 `protobuf:"bytes,16,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Pattern       *RecurrencePattern     `protobuf:"bytes,17,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	Rdates        []string               `protobuf:"bytes,18,rep,name=rdates,proto3" json:"rdates,omitempty"`
	Exdates       []string               `protobuf:"bytes,19,rep,name=exdates,proto3" json:"exdates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{22}
}

func (x *CreateReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReservationRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CreateReservationRequest) GetFacilityId() int64 {
	if x != nil {
		return x.FacilityId
	}
	return 0
}

func (x *CreateReservationRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *CreateReservationRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateReservationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReservationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateReservationRequest) GetTechSupport() bool {
	if x != nil {
		return x.TechSupport
	}
	return false
}

func (x *CreateReservationRequest) GetTechDetails() string {
	if x != nil && x.TechDetails != nil {
		return *x.TechDetails
	}
	return ""
}

func (x *CreateReservationRequest) GetDoorAccess() bool {
	if x != nil {
		return x.DoorAccess
	}
	return false
}

func (x *CreateReservationRequest) GetDoorsDetails() string {
	if x != nil && x.DoorsDetails != nil {
		return *x.DoorsDetails
	}
	return ""
}

func (x *CreateReservationRequest) GetOccurrences() []*Occurrence {
	if x != nil {
		return x.Occurrences
	}
	return nil
}

func (x *CreateReservationRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateReservationRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateReservationRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateReservationRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateReservationRequest) GetPattern() *RecurrencePattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *CreateReservationRequest) GetRdates() []string {
	if x != nil {
		return x.Rdates
	}
	return nil
}

func (x *CreateReservationRequest) GetExdates() []string {
	if x != nil {
		return x.Exdates
	}
	return nil
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{23}
}

func (x *CreateReservationResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationRequest) Reset() {
	*x = UpdateReservationRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationRequest) ProtoMessage() {}

func (x *UpdateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationRequest.ProtoReflect.Descriptor instead.
func (*UpdateReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateReservationRequest) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type UpdateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationResponse) Reset() {
	*x = UpdateReservationResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationResponse) ProtoMessage() {}

func (x *UpdateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationResponse.ProtoReflect.Descriptor instead.
func (*UpdateReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{25}
}

type DeleteReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationRequest) Reset() {
	*x = DeleteReservationRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationRequest) ProtoMessage() {}

func (x *DeleteReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationRequest.ProtoReflect.Descriptor instead.
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteReservationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationResponse) Reset() {
	*x = DeleteReservationResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationResponse) ProtoMessage() {}

func (x *DeleteReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationResponse.ProtoReflect.Descriptor instead.
func (*DeleteReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{27}
}

type UserReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReservationsRequest) Reset() {
	*x = UserReservationsRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReservationsRequest) ProtoMessage() {}

func (x *UserReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReservationsRequest.ProtoReflect.Descriptor instead.
func (*UserReservationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{28}
}

func (x *UserReservationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateReservationDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          []*ReservationDate     `protobuf:"bytes,1,rep,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationDatesRequest) Reset() {
	*x = CreateReservationDatesRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationDatesRequest) ProtoMessage() {}

func (x *CreateReservationDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationDatesRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationDatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{29}
}

func (x *CreateReservationDatesRequest) GetDate() []*ReservationDate {
	if x != nil {
		return x.Date
	}
	return nil
}

type CreateReservationDatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationDatesResponse) Reset() {
	*x = CreateReservationDatesResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationDatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationDatesResponse) ProtoMessage() {}

func (x *CreateReservationDatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationDatesResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationDatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{30}
}

type UpdateReservationDatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationDatesResponse) Reset() {
	*x = UpdateReservationDatesResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationDatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationDatesResponse) ProtoMessage() {}

func (x *UpdateReservationDatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationDatesResponse.ProtoReflect.Descriptor instead.
func (*UpdateReservationDatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{31}
}

type DeleteReservationDatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationDatesResponse) Reset() {
	*x = DeleteReservationDatesResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationDatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationDatesResponse) ProtoMessage() {}

func (x *DeleteReservationDatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationDatesResponse.ProtoReflect.Descriptor instead.
func (*DeleteReservationDatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{32}
}

type CreateReservationFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationFeeResponse) Reset() {
	*x = CreateReservationFeeResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationFeeResponse) ProtoMessage() {}

func (x *CreateReservationFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationFeeResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationFeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{33}
}

type UpdateReservationFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationFeeResponse) Reset() {
	*x = UpdateReservationFeeResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationFeeResponse) ProtoMessage() {}

func (x *UpdateReservationFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationFeeResponse.ProtoReflect.Descriptor instead.
func (*UpdateReservationFeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{34}
}

type DeleteReservationFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationFeeResponse) Reset() {
	*x = DeleteReservationFeeResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationFeeResponse) ProtoMessage() {}

func (x *DeleteReservationFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationFeeResponse.ProtoReflect.Descriptor instead.
func (*DeleteReservationFeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{35}
}

type UpdateReservationDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          []*ReservationDate     `protobuf:"bytes,1,rep,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationDatesRequest) Reset() {
	*x = UpdateReservationDatesRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationDatesRequest) ProtoMessage() {}

func (x *UpdateReservationDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationDatesRequest.ProtoReflect.Descriptor instead.
func (*UpdateReservationDatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateReservationDatesRequest) GetDate() []*ReservationDate {
	if x != nil {
		return x.Date
	}
	return nil
}

type DeleteReservationDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int64                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationDatesRequest) Reset() {
	*x = DeleteReservationDatesRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationDatesRequest) ProtoMessage() {}

func (x *DeleteReservationDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationDatesRequest.ProtoReflect.Descriptor instead.
func (*DeleteReservationDatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteReservationDatesRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type CreateReservationFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fee           []*ReservationFee      `protobuf:"bytes,1,rep,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationFeeRequest) Reset() {
	*x = CreateReservationFeeRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationFeeRequest) ProtoMessage() {}

func (x *CreateReservationFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationFeeRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationFeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{38}
}

func (x *CreateReservationFeeRequest) GetFee() []*ReservationFee {
	if x != nil {
		return x.Fee
	}
	return nil
}

type UpdateReservationFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fee           *ReservationFee        `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReservationFeeRequest) Reset() {
	*x = UpdateReservationFeeRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReservationFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReservationFeeRequest) ProtoMessage() {}

func (x *UpdateReservationFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReservationFeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateReservationFeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{39}
}

func (x *UpdateReservationFeeRequest) GetFee() *ReservationFee {
	if x != nil {
		return x.Fee
	}
	return nil
}

type DeleteReservationFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationFeeRequest) Reset() {
	*x = DeleteReservationFeeRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationFeeRequest) ProtoMessage() {}

func (x *DeleteReservationFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationFeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteReservationFeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{40}
}

func (x *DeleteReservationFeeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CostReducerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostReducerRequest) Reset() {
	*x = CostReducerRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostReducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReducerRequest) ProtoMessage() {}

func (x *CostReducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReducerRequest.ProtoReflect.Descriptor instead.
func (*CostReducerRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{41}
}

func (x *CostReducerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CostReducerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          string                 `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostReducerResponse) Reset() {
	*x = CostReducerResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostReducerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReducerResponse) ProtoMessage() {}

func (x *CostReducerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReducerResponse.ProtoReflect.Descriptor instead.
func (*CostReducerResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{42}
}

func (x *CostReducerResponse) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

var File_proto_reservation_reservation_proto protoreflect.FileDescriptor

const file_proto_reservation_reservation_proto_rawDesc = "" +
	"\n" +
	"#proto/reservation/reservation.proto\x12\x0fapi.reservation\"\xcb\b\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12\x1f\n" +
	"\vfacility_id\x18\x04 \x01(\x03R\n" +
	"facilityId\x12\x1a\n" +
	"\bapproved\x18\x05 \x01(\tR\bapproved\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\adetails\x18\b \x01(\tH\x00R\adetails\x88\x01\x01\x12\x12\n" +
	"\x04fees\x18\t \x01(\tR\x04fees\x12\x1c\n" +
	"\tinsurance\x18\n" +
	" \x01(\bR\tinsurance\x12$\n" +
	"\vdoor_access\x18\v \x01(\bH\x01R\n" +
	"doorAccess\x88\x01\x01\x12(\n" +
	"\rdoors_details\x18\f \x01(\tH\x02R\fdoorsDetails\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\r \x01(\tH\x03R\x04name\x88\x01\x01\x12&\n" +
	"\ftech_details\x18\x0e \x01(\tH\x04R\vtechDetails\x88\x01\x01\x12&\n" +
	"\ftech_support\x18\x0f \x01(\bH\x05R\vtechSupport\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x10 \x01(\tH\x06R\x05phone\x88\x01\x01\x12\x1f\n" +
	"\vcategory_id\x18\x11 \x01(\x03R\n" +
	"categoryId\x12$\n" +
	"\vtotal_hours\x18\x12 \x01(\x01H\aR\n" +
	"totalHours\x88\x01\x01\x12\x1b\n" +
	"\tin_person\x18\x13 \x01(\bR\binPerson\x12\x12\n" +
	"\x04paid\x18\x14 \x01(\bR\x04paid\x12$\n" +
	"\vpayment_url\x18\x15 \x01(\tH\bR\n" +
	"paymentUrl\x88\x01\x01\x12+\n" +
	"\x0fpayment_link_id\x18\x16 \x01(\tH\tR\rpaymentLinkId\x88\x01\x01\x12*\n" +
	"\x0einsurance_link\x18\x17 \x01(\tH\n" +
	"R\rinsuranceLink\x88\x01\x01\x12#\n" +
	"\rcost_override\x18\x18 \x01(\tR\fcostOverride\x12\x19\n" +
	"\x05rrule\x18\x19 \x01(\tH\vR\x05rrule\x88\x01\x01\x12\x16\n" +
	"\x06rdates\x18\x1a \x03(\tR\x06rdates\x12\x18\n" +
	"\aexdates\x18\x1b \x03(\tR\aexdates\x12&\n" +
	"\fgcal_eventid\x18\x1c \x01(\tH\fR\vgcalEventid\x88\x01\x01B\n" +
	"\n" +
	"\b_detailsB\x0e\n" +
	"\f_door_accessB\x10\n" +
	"\x0e_doors_detailsB\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_tech_detailsB\x0f\n" +
	"\r_tech_supportB\b\n" +
	"\x06_phoneB\x0e\n" +
	"\f_total_hoursB\x0e\n" +
	"\f_payment_urlB\x12\n" +
	"\x10_payment_link_idB\x11\n" +
	"\x0f_insurance_linkB\b\n" +
	"\x06_rruleB\x0f\n" +
	"\r_gcal_eventid\"\xdb\x01\n" +
	"\x0fReservationDate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\x03R\rreservationId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\tR\bapproved\x12&\n" +
	"\fgcal_eventid\x18\x04 \x01(\tH\x00R\vgcalEventid\x88\x01\x01\x12\x1f\n" +
	"\vlocal_start\x18\x05 \x01(\tR\n" +
	"localStart\x12\x1b\n" +
	"\tlocal_end\x18\x06 \x01(\tR\blocalEndB\x0f\n" +
	"\r_gcal_eventid\"r\n" +
	"\x11RecurrencePattern\x12\x12\n" +
	"\x04freq\x18\x01 \x01(\tR\x04freq\x12\x1d\n" +
	"\n" +
	"by_weekday\x18\x02 \x03(\tR\tbyWeekday\x12\x14\n" +
	"\x05until\x18\x03 \x01(\tR\x05until\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"4\n" +
	"\n" +
	"Occurrence\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\"\xa0\x01\n" +
	"\x0eReservationFee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fadditional_fees\x18\x02 \x01(\tR\x0eadditionalFees\x12 \n" +
	"\tfees_type\x18\x03 \x01(\tH\x00R\bfeesType\x88\x01\x01\x12%\n" +
	"\x0ereservation_id\x18\x04 \x01(\x03R\rreservationIdB\f\n" +
	"\n" +
	"_fees_type\"\xbe\x01\n" +
	"\x0fFullReservation\x12>\n" +
	"\vreservation\x18\x01 \x01(\v2\x1c.api.reservation.ReservationR\vreservation\x126\n" +
	"\x05dates\x18\x02 \x03(\v2 .api.reservation.ReservationDateR\x05dates\x123\n" +
	"\x04fees\x18\x03 \x03(\v2\x1f.api.reservation.ReservationFeeR\x04fees\"\xea\x01\n" +
	"\x17FullResWithFacilityName\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12#\n" +
	"\rfacility_name\x18\x02 \x01(\tR\ffacilityName\x12)\n" +
	"\x10reservation_date\x18\x03 \x01(\tR\x0freservationDate\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\tR\bapproved\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12'\n" +
	"\x0fresrervation_id\x18\x06 \x01(\x03R\x0eresrervationId\"R\n" +
	"\x12AllPendingResponse\x12<\n" +
	"\x04data\x18\x01 \x03(\v2(.api.reservation.FullResWithFacilityNameR\x04data\"\x93\x01\n" +
	"\x11AllSortedResponse\x12<\n" +
	"\x04past\x18\x01 \x03(\v2(.api.reservation.FullResWithFacilityNameR\x04past\x12@\n" +
	"\x06future\x18\x02 \x03(\v2(.api.reservation.FullResWithFacilityNameR\x06future\"H\n" +
	"\x1eUpdateReservationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"O\n" +
	"#UpdateReservationDatesStatusRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"&\n" +
	"$UpdateReservationDatesStatusResponse\"_\n" +
	"\x17AllReservationsResponse\x12D\n" +
	"\freservations\x18\x01 \x03(\v2 .api.reservation.FullReservationR\freservations\"_\n" +
	"\x17RequestThisWeekResponse\x12D\n" +
	"\freservations\x18\x01 \x03(\v2 .api.reservation.FullReservationR\freservations\"d\n" +
	"\x1cApprovedReservationsResponse\x12D\n" +
	"\freservations\x18\x01 \x03(\v2 .api.reservation.FullReservationR\freservations\"c\n" +
	"\x1bPendingReservationsResponse\x12D\n" +
	"\freservations\x18\x01 \x03(\v2 .api.reservation.FullReservationR\freservations\"`\n" +
	"\x18UserReservationsResponse\x12D\n" +
	"\freservations\x18\x01 \x03(\v2 .api.reservation.FullReservationR\freservations\"\x1b\n" +
	"\x19GetAllReservationsRequest\"'\n" +
	"\x15GetReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13RequestCountRequest\",\n" +
	"\x14RequestCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x1c\n" +
	"\x1aGetRequestsThisWeekRequest\"\xc5\x05\n" +
	"\x18CreateReservationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12\x1f\n" +
	"\vfacility_id\x18\x03 \x01(\x03R\n" +
	"facilityId\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12!\n" +
	"\ftech_support\x18\b \x01(\bR\vtechSupport\x12&\n" +
	"\ftech_details\x18\t \x01(\tH\x00R\vtechDetails\x88\x01\x01\x12\x1f\n" +
	"\vdoor_access\x18\n" +
	" \x01(\bR\n" +
	"doorAccess\x12(\n" +
	"\rdoors_details\x18\v \x01(\tH\x01R\fdoorsDetails\x88\x01\x01\x12=\n" +
	"\voccurrences\x18\f \x03(\v2\x1b.api.reservation.OccurrenceR\voccurrences\x12\x1d\n" +
	"\n" +
	"start_date\x18\r \x01(\tR\tstartDate\x12\x1d\n" +
	"\n" +
	"start_time\x18\x0e \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_date\x18\x0f \x01(\tR\aendDate\x12\x19\n" +
	"\bend_time\x18\x10 \x01(\tR\aendTime\x12A\n" +
	"\apattern\x18\x11 \x01(\v2\".api.reservation.RecurrencePatternH\x02R\apattern\x88\x01\x01\x12\x16\n" +
	"\x06rdates\x18\x12 \x03(\tR\x06rdates\x12\x18\n" +
	"\aexdates\x18\x13 \x03(\tR\aexdatesB\x0f\n" +
	"\r_tech_detailsB\x10\n" +
	"\x0e_doors_detailsB\n" +
	"\n" +
	"\b_pattern\"+\n" +
	"\x19CreateReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Z\n" +
	"\x18UpdateReservationRequest\x12>\n" +
	"\vreservation\x18\x01 \x01(\v2\x1c.api.reservation.ReservationR\vreservation\"\x1b\n" +
	"\x19UpdateReservationResponse\"*\n" +
	"\x18DeleteReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1b\n" +
	"\x19DeleteReservationResponse\"2\n" +
	"\x17UserReservationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\x1dCreateReservationDatesRequest\x124\n" +
	"\x04date\x18\x01 \x03(\v2 .api.reservation.ReservationDateR\x04date\" \n" +
	"\x1eCreateReservationDatesResponse\" \n" +
	"\x1eUpdateReservationDatesResponse\" \n" +
	"\x1eDeleteReservationDatesResponse\"\x1e\n" +
	"\x1cCreateReservationFeeResponse\"\x1e\n" +
	"\x1cUpdateReservationFeeResponse\"\x1e\n" +
	"\x1cDeleteReservationFeeResponse\"U\n" +
	"\x1dUpdateReservationDatesRequest\x124\n" +
	"\x04date\x18\x01 \x03(\v2 .api.reservation.ReservationDateR\x04date\"/\n" +
	"\x1dDeleteReservationDatesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x03R\x02id\"P\n" +
	"\x1bCreateReservationFeeRequest\x121\n" +
	"\x03fee\x18\x01 \x03(\v2\x1f.api.reservation.ReservationFeeR\x03fee\"P\n" +
	"\x1bUpdateReservationFeeRequest\x121\n" +
	"\x03fee\x18\x01 \x01(\v2\x1f.api.reservation.ReservationFeeR\x03fee\"-\n" +
	"\x1bDeleteReservationFeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12CostReducerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\x13CostReducerResponse\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\tR\x04cost2\xf2\x10\n" +
	"\x12ReservationService\x12o\n" +
	"\x12GetAllReservations\x12*.api.reservation.GetAllReservationsRequest\x1a(.api.reservation.AllReservationsResponse\"\x03\x90\x02\x01\x12_\n" +
	"\x0eGetReservation\x12&.api.reservation.GetReservationRequest\x1a .api.reservation.FullReservation\"\x03\x90\x02\x01\x12`\n" +
	"\fRequestCount\x12$.api.reservation.RequestCountRequest\x1a%.api.reservation.RequestCountResponse\"\x03\x90\x02\x01\x12q\n" +
	"\x13GetRequestsThisWeek\x12+.api.reservation.GetRequestsThisWeekRequest\x1a(.api.reservation.RequestThisWeekResponse\"\x03\x90\x02\x01\x12j\n" +
	"\x11CreateReservation\x12).api.reservation.CreateReservationRequest\x1a*.api.reservation.CreateReservationResponse\x12j\n" +
	"\x11UpdateReservation\x12).api.reservation.UpdateReservationRequest\x1a*.api.reservation.UpdateReservationResponse\x12v\n" +
	"\x17UpdateReservationStatus\x12/.api.reservation.UpdateReservationStatusRequest\x1a*.api.reservation.UpdateReservationResponse\x12j\n" +
	"\x11DeleteReservation\x12).api.reservation.DeleteReservationRequest\x1a*.api.reservation.DeleteReservationResponse\x12l\n" +
	"\x10UserReservations\x12(.api.reservation.UserReservationsRequest\x1a).api.reservation.UserReservationsResponse\"\x03\x90\x02\x01\x12y\n" +
	"\x16CreateReservationDates\x12..api.reservation.CreateReservationDatesRequest\x1a/.api.reservation.CreateReservationDatesResponse\x12y\n" +
	"\x16UpdateReservationDates\x12..api.reservation.UpdateReservationDatesRequest\x1a/.api.reservation.UpdateReservationDatesResponse\x12\x8b\x01\n" +
	"\x1cUpdateReservationDatesStatus\x124.api.reservation.UpdateReservationDatesStatusRequest\x1a5.api.reservation.UpdateReservationDatesStatusResponse\x12y\n" +
	"\x16DeleteReservationDates\x12..api.reservation.DeleteReservationDatesRequest\x1a/.api.reservation.DeleteReservationDatesResponse\x12s\n" +
	"\x14CreateReservationFee\x12,.api.reservation.CreateReservationFeeRequest\x1a-.api.reservation.CreateReservationFeeResponse\x12s\n" +
	"\x14UpdateReservationFee\x12,.api.reservation.UpdateReservationFeeRequest\x1a-.api.reservation.UpdateReservationFeeResponse\x12s\n" +
	"\x14DeleteReservationFee\x12,.api.reservation.DeleteReservationFeeRequest\x1a-.api.reservation.DeleteReservationFeeResponse\x12X\n" +
	"\vCostReducer\x12#.api.reservation.CostReducerRequest\x1a$.api.reservation.CostReducerResponse\x12e\n" +
	"\rGetAllPending\x12*.api.reservation.GetAllReservationsRequest\x1a#.api.reservation.AllPendingResponse\"\x03\x90\x02\x01\x12l\n" +
	"\x15AllSortedReservations\x12*.api.reservation.GetAllReservationsRequest\x1a\".api.reservation.AllSortedResponse\"\x03\x90\x02\x01B3Z1api/internal/proto/reservation;reservationserviceb\x06proto3"

var (
	file_proto_reservation_reservation_proto_rawDescOnce sync.Once
	file_proto_reservation_reservation_proto_rawDescData []byte
)

func file_proto_reservation_reservation_proto_rawDescGZIP() []byte {
	file_proto_reservation_reservation_proto_rawDescOnce.Do(func() {
		file_proto_reservation_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reservation_reservation_proto_rawDesc), len(file_proto_reservation_reservation_proto_rawDesc)))
	})
	return file_proto_reservation_reservation_proto_rawDescData
}

var file_proto_reservation_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_proto_reservation_reservation_proto_goTypes = []any{
	(*Reservation)(nil),                          // 0: api.reservation.Reservation
	(*ReservationDate)(nil),                      // 1: api.reservation.ReservationDate
	(*RecurrencePattern)(nil),                    // 2: api.reservation.RecurrencePattern
	(*Occurrence)(nil),                           // 3: api.reservation.Occurrence
	(*ReservationFee)(nil),                       // 4: api.reservation.ReservationFee
	(*FullReservation)(nil),                      // 5: api.reservation.FullReservation
	(*FullResWithFacilityName)(nil),              // 6: api.reservation.FullResWithFacilityName
	(*AllPendingResponse)(nil),                   // 7: api.reservation.AllPendingResponse
	(*AllSortedResponse)(nil),                    // 8: api.reservation.AllSortedResponse
	(*UpdateReservationStatusRequest)(nil),       // 9: api.reservation.UpdateReservationStatusRequest
	(*UpdateReservationDatesStatusRequest)(nil),  // 10: api.reservation.UpdateReservationDatesStatusRequest
	(*UpdateReservationDatesStatusResponse)(nil), // 11: api.reservation.UpdateReservationDatesStatusResponse
	(*AllReservationsResponse)(nil),              // 12: api.reservation.AllReservationsResponse
	(*RequestThisWeekResponse)(nil),              // 13: api.reservation.RequestThisWeekResponse
	(*ApprovedReservationsResponse)(nil),         // 14: api.reservation.ApprovedReservationsResponse
	(*PendingReservationsResponse)(nil),          // 15: api.reservation.PendingReservationsResponse
	(*UserReservationsResponse)(nil),             // 16: api.reservation.UserReservationsResponse
	(*GetAllReservationsRequest)(nil),            // 17: api.reservation.GetAllReservationsRequest
	(*GetReservationRequest)(nil),                // 18: api.reservation.GetReservationRequest
	(*RequestCountRequest)(nil),                  // 19: api.reservation.RequestCountRequest
	(*RequestCountResponse)(nil),                 // 20: api.reservation.RequestCountResponse
	(*GetRequestsThisWeekRequest)(nil),           // 21: api.reservation.GetRequestsThisWeekRequest
	(*CreateReservationRequest)(nil),             // 22: api.reservation.CreateReservationRequest
	(*CreateReservationResponse)(nil),            // 23: api.reservation.CreateReservationResponse
	(*UpdateReservationRequest)(nil),             // 24: api.reservation.UpdateReservationRequest
	(*UpdateReservationResponse)(nil),            // 25: api.reservation.UpdateReservationResponse
	(*DeleteReservationRequest)(nil),             // 26: api.reservation.DeleteReservationRequest
	(*DeleteReservationResponse)(nil),            // 27: api.reservation.DeleteReservationResponse
	(*UserReservationsRequest)(nil),              // 28: api.reservation.UserReservationsRequest
	(*CreateReservationDatesRequest)(nil),        // 29: api.reservation.CreateReservationDatesRequest
	(*CreateReservationDatesResponse)(nil),       // 30: api.reservation.CreateReservationDatesResponse
	(*UpdateReservationDatesResponse)(nil),       // 31: api.reservation.UpdateReservationDatesResponse
	(*DeleteReservationDatesResponse)(nil),       // 32: api.reservation.DeleteReservationDatesResponse
	(*CreateReservationFeeResponse)(nil),         // 33: api.reservation.CreateReservationFeeResponse
	(*UpdateReservationFeeResponse)(nil),         // 34: api.reservation.UpdateReservationFeeResponse
	(*DeleteReservationFeeResponse)(nil),         // 35: api.reservation.DeleteReservationFeeResponse
	(*UpdateReservationDatesRequest)(nil),        // 36: api.reservation.UpdateReservationDatesRequest
	(*DeleteReservationDatesRequest)(nil),        // 37: api.reservation.DeleteReservationDatesRequest
	(*CreateReservationFeeRequest)(nil),          // 38: api.reservation.CreateReservationFeeRequest
	(*UpdateReservationFeeRequest)(nil),          // 39: api.reservation.UpdateReservationFeeRequest
	(*DeleteReservationFeeRequest)(nil),          // 40: api.reservation.DeleteReservationFeeRequest
	(*CostReducerRequest)(nil),                   // 41: api.reservation.CostReducerRequest
	(*CostReducerResponse)(nil),                  // 42: api.reservation.CostReducerResponse
}
var file_proto_reservation_reservation_proto_depIdxs = []int32{
	0,  // 0: api.reservation.FullReservation.reservation:type_name -> api.reservation.Reservation
	1,  // 1: api.reservation.FullReservation.dates:type_name -> api.reservation.ReservationDate
	4,  // 2: api.reservation.FullReservation.fees:type_name -> api.reservation.ReservationFee
	6,  // 3: api.reservation.AllPendingResponse.data:type_name -> api.reservation.FullResWithFacilityName
	6,  // 4: api.reservation.AllSortedResponse.past:type_name -> api.reservation.FullResWithFacilityName
	6,  // 5: api.reservation.AllSortedResponse.future:type_name -> api.reservation.FullResWithFacilityName
	5,  // 6: api.reservation.AllReservationsResponse.reservations:type_name -> api.reservation.FullReservation
	5,  // 7: api.reservation.RequestThisWeekResponse.reservations:type_name -> api.reservation.FullReservation
	5,  // 8: api.reservation.ApprovedReservationsResponse.reservations:type_name -> api.reservation.FullReservation
	5,  // 9: api.reservation.PendingReservationsResponse.reservations:type_name -> api.reservation.FullReservation
	5,  // 10: api.reservation.UserReservationsResponse.reservations:type_name -> api.reservation.FullReservation
	3,  // 11: api.reservation.CreateReservationRequest.occurrences:type_name -> api.reservation.Occurrence
	2,  // 12: api.reservation.CreateReservationRequest.pattern:type_name -> api.reservation.RecurrencePattern
	0,  // 13: api.reservation.UpdateReservationRequest.reservation:type_name -> api.reservation.Reservation
	1,  // 14: api.reservation.CreateReservationDatesRequest.date:type_name -> api.reservation.ReservationDate
	1,  // 15: api.reservation.UpdateReservationDatesRequest.date:type_name -> api.reservation.ReservationDate
	4,  // 16: api.reservation.CreateReservationFeeRequest.fee:type_name -> api.reservation.ReservationFee
	4,  // 17: api.reservation.UpdateReservationFeeRequest.fee:type_name -> api.reservation.ReservationFee
	17, // 18: api.reservation.ReservationService.GetAllReservations:input_type -> api.reservation.GetAllReservationsRequest
	18, // 19: api.reservation.ReservationService.GetReservation:input_type -> api.reservation.GetReservationRequest
	19, // 20: api.reservation.ReservationService.RequestCount:input_type -> api.reservation.RequestCountRequest
	21, // 21: api.reservation.ReservationService.GetRequestsThisWeek:input_type -> api.reservation.GetRequestsThisWeekRequest
	22, // 22: api.reservation.ReservationService.CreateReservation:input_type -> api.reservation.CreateReservationRequest
	24, // 23: api.reservation.ReservationService.UpdateReservation:input_type -> api.reservation.UpdateReservationRequest
	9,  // 24: api.reservation.ReservationService.UpdateReservationStatus:input_type -> api.reservation.UpdateReservationStatusRequest
	26, // 25: api.reservation.ReservationService.DeleteReservation:input_type -> api.reservation.DeleteReservationRequest
	28, // 26: api.reservation.ReservationService.UserReservations:input_type -> api.reservation.UserReservationsRequest
	29, // 27: api.reservation.ReservationService.CreateReservationDates:input_type -> api.reservation.CreateReservationDatesRequest
	36, // 28: api.reservation.ReservationService.UpdateReservationDates:input_type -> api.reservation.UpdateReservationDatesRequest
	10, // 29: api.reservation.ReservationService.UpdateReservationDatesStatus:input_type -> api.reservation.UpdateReservationDatesStatusRequest
	37, // 30: api.reservation.ReservationService.DeleteReservationDates:input_type -> api.reservation.DeleteReservationDatesRequest
	38, // 31: api.reservation.ReservationService.CreateReservationFee:input_type -> api.reservation.CreateReservationFeeRequest
	39, // 32: api.reservation.ReservationService.UpdateReservationFee:input_type -> api.reservation.UpdateReservationFeeRequest
	40, // 33: api.reservation.ReservationService.DeleteReservationFee:input_type -> api.reservation.DeleteReservationFeeRequest
	41, // 34: api.reservation.ReservationService.CostReducer:input_type -> api.reservation.CostReducerRequest
	17, // 35: api.reservation.ReservationService.GetAllPending:input_type -> api.reservation.GetAllReservationsRequest
	17, // 36: api.reservation.ReservationService.AllSortedReservations:input_type -> api.reservation.GetAllReservationsRequest
	12, // 37: api.reservation.ReservationService.GetAllReservations:output_type -> api.reservation.AllReservationsResponse
	5,  // 38: api.reservation.ReservationService.GetReservation:output_type -> api.reservation.FullReservation
	20, // 39: api.reservation.ReservationService.RequestCount:output_type -> api.reservation.RequestCountResponse
	13, // 40: api.reservation.ReservationService.GetRequestsThisWeek:output_type -> api.reservation.RequestThisWeekResponse
	23, // 41: api.reservation.ReservationService.CreateReservation:output_type -> api.reservation.CreateReservationResponse
	25, // 42: api.reservation.ReservationService.UpdateReservation:output_type -> api.reservation.UpdateReservationResponse
	25, // 43: api.reservation.ReservationService.UpdateReservationStatus:output_type -> api.reservation.UpdateReservationResponse
	27, // 44: api.reservation.ReservationService.DeleteReservation:output_type -> api.reservation.DeleteReservationResponse
	16, // 45: api.reservation.ReservationService.UserReservations:output_type -> api.reservation.UserReservationsResponse
	30, // 46: api.reservation.ReservationService.CreateReservationDates:output_type -> api.reservation.CreateReservationDatesResponse
	31, // 47: api.reservation.ReservationService.UpdateReservationDates:output_type -> api.reservation.UpdateReservationDatesResponse
	11, // 48: api.reservation.ReservationService.UpdateReservationDatesStatus:output_type -> api.reservation.UpdateReservationDatesStatusResponse
	32, // 49: api.reservation.ReservationService.DeleteReservationDates:output_type -> api.reservation.DeleteReservationDatesResponse
	33, // 50: api.reservation.ReservationService.CreateReservationFee:output_type -> api.reservation.CreateReservationFeeResponse
	34, // 51: api.reservation.ReservationService.UpdateReservationFee:output_type -> api.reservation.UpdateReservationFeeResponse
	35, // 52: api.reservation.ReservationService.DeleteReservationFee:output_type -> api.reservation.DeleteReservationFeeResponse
	42, // 53: api.reservation.ReservationService.CostReducer:output_type -> api.reservation.CostReducerResponse
	7,  // 54: api.reservation.ReservationService.GetAllPending:output_type -> api.reservation.AllPendingResponse
	8,  // 55: api.reservation.ReservationService.AllSortedReservations:output_type -> api.reservation.AllSortedResponse
	37, // [37:56] is the sub-list for method output_type
	18, // [18:37] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_reservation_reservation_proto_init() }
func file_proto_reservation_reservation_proto_init() {
	if File_proto_reservation_reservation_proto != nil {
		return
	}
	file_proto_reservation_reservation_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_reservation_reservation_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_reservation_reservation_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_reservation_reservation_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reservation_reservation_proto_rawDesc), len(file_proto_reservation_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reservation_reservation_proto_goTypes,
		DependencyIndexes: file_proto_reservation_reservation_proto_depIdxs,
		MessageInfos:      file_proto_reservation_reservation_proto_msgTypes,
	}.Build()
	File_proto_reservation_reservation_proto = out.File
	file_proto_reservation_reservation_proto_goTypes = nil
	file_proto_reservation_reservation_proto_depIdxs = nil
}
