ALTER TABLE sessions
  DROP COLUMN IF EXISTS session_token,
  DROP COLUMN IF EXISTS expires,
  ADD COLUMN IF NOT EXISTS refresh_token TEXT,
  ADD COLUMN IF NOT EXISTS provider TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '1 day');

ALTER TABLE reservation DROP CONSTRAINT IF EXISTS fk_user_id;
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS fk_user_id;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS fk_user_id;



ALTER TABLE reservation
  ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE notifications
  ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sessions
  ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;


CREATE TABLE IF NOT EXISTS building (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  google_calendar_id TEXT
);

ALTER TABLE facility ADD COLUMN IF NOT EXISTS building_id BIGINT;

ALTER TABLE facility
  ADD CONSTRAINT fk_building_id FOREIGN KEY (building_id) REFERENCES building (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE notifications 
  DROP CONSTRAINT IF EXISTS fk_facility_id,
  DROP COLUMN IF EXISTS facility_id,
  DROP COLUMN IF EXISTS building,
  ADD COLUMN IF NOT EXISTS building_id BIGINT;

ALTER TABLE notifications
  ADD CONSTRAINT fk_building_id FOREIGN KEY (building_id) REFERENCES building (id) ON UPDATE CASCADE ON DELETE CASCADE;


