ALTER TABLE sessions
  DROP COLUMN IF EXISTS session_token
  DROP COLUMN IF EXISTS expires
  ADD COLUMN IF NOT EXISTS refresh_token TEXT
  ADD COLUMN IF NOT EXISTS provider TEXT
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NOT NULL;

ALTER TABLE account DROP CONSTRAINT IF EXISTS fk_user_id;
ALTER TABLE reservation DROP CONSTRAINT IF EXISTS fk_user_id;
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS fk_user_id;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS fk_user_id;
DROP TABLE account;



ALTER TABLE reservation
  ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE notifications
  ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sessions
  ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;
