ALTER TABLE sessions
  DROP COLUMN IF EXISTS session_token
  DROP COLUMN IF EXISTS expires
  ADD COLUMN IF NOT EXISTS refresh_token TEXT
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NOT NULL;
