version: "2"
run:
  tests: false
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - bodyclose
    - goconst
    - goprintffuncname
    - gosec
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - unconvert
  disable:
    - staticcheck
  settings:
    gosec:
      excludes:
        - G115
        - G404
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'G404: Use of weak random number generator'
      - path: (.+)\.go$
        text: 'G115: Integer overflow conversion'
    paths:
      - cli
      - cmd/script
      - third_party$
      - builtin$
      - scripts$
      - examples$
      - tmp$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
